package BackEnd;

import java.awt.*;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.JLabel;

/**
 *
 * @author USER
 */
public class PelangganAdmin extends javax.swing.JFrame {

    /**
     * Creates new form PelangganAdmin
     */
    public PelangganAdmin() {
        initComponents();
        // admin = new Admin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pelangganPanel = new javax.swing.JPanel();
        labelPilihPelanggan = new javax.swing.JLabel();
        teksNama = new javax.swing.JTextField();
        labelTanggalDaftarPelanggan = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        buttonTambahPelanggan = new javax.swing.JButton();
        buttonHapusPelanggan = new javax.swing.JButton();
        buttonUpdatePelanggan = new javax.swing.JButton();
        labelNomorPelanggan = new javax.swing.JLabel();
        teksIDPelanggan = new javax.swing.JTextField();
        buttonBack = new javax.swing.JButton();
        pelangganLabel = new javax.swing.JLabel();
        labelNamaPelanggan1 = new javax.swing.JLabel();
        teksTanggalDaftarPelanggan = new javax.swing.JTextField();
        labelNamaPelanggan2 = new javax.swing.JLabel();
        teksNama2 = new javax.swing.JTextField();
        tanggalFormat = new JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pelangganPanel.setBackground(new java.awt.Color(52, 73, 94));

        labelPilihPelanggan.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        labelPilihPelanggan.setForeground(new java.awt.Color(255, 255, 255));
        labelPilihPelanggan.setText("Pilih Pelanggan");

        teksNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teksNamaActionPerformed(evt);
            }
        });

        labelTanggalDaftarPelanggan.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        labelTanggalDaftarPelanggan.setForeground(new java.awt.Color(255, 255, 255));
        labelTanggalDaftarPelanggan.setText("Tanggal daftar");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MEMBER", "GUEST" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        buttonTambahPelanggan.setText("Tambah");
        buttonTambahPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahPelangganActionPerformed(evt);
            }
        });

        buttonHapusPelanggan.setText("Hapus");

        buttonUpdatePelanggan.setText("Update");
        buttonUpdatePelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdatePelangganActionPerformed(evt);
            }
        });

        labelNomorPelanggan.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        labelNomorPelanggan.setForeground(new java.awt.Color(255, 255, 255));
        labelNomorPelanggan.setText("ID Pelanggan");

        teksIDPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teksIDPelangganActionPerformed(evt);
            }
        });

        buttonBack.setText("back");
        buttonBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonBackMouseClicked(evt);
            }
        });

        pelangganLabel.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        pelangganLabel.setForeground(new java.awt.Color(255, 255, 255));
        pelangganLabel.setText("PELANGGAN");

        labelNamaPelanggan1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        labelNamaPelanggan1.setForeground(new java.awt.Color(255, 255, 255));
        labelNamaPelanggan1.setText("Nama Pelanggan");

        teksTanggalDaftarPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teksTanggalDaftarPelangganActionPerformed(evt);
            }
        });

        labelNamaPelanggan2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        labelNamaPelanggan2.setForeground(new java.awt.Color(255, 255, 255));
        labelNamaPelanggan2.setText("Saldo Awal");

        teksNama2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teksNama2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pelangganPanelLayout = new javax.swing.GroupLayout(pelangganPanel);
        pelangganPanel.setLayout(pelangganPanelLayout);
        pelangganPanelLayout.setHorizontalGroup(
                pelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pelangganPanelLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(pelangganPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(pelangganPanelLayout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(labelNomorPelanggan)
                                                .addComponent(labelNamaPelanggan1)
                                                .addComponent(labelPilihPelanggan)
                                                .addComponent(labelTanggalDaftarPelanggan)
                                                .addComponent(labelNamaPelanggan2))
                                        .addGroup(pelangganPanelLayout.createSequentialGroup()
                                                .addComponent(buttonTambahPelanggan)
                                                .addGap(34, 34, 34)))
                                .addGap(18, 18, 18)
                                .addGroup(pelangganPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pelangganPanelLayout.createSequentialGroup()
                                                .addGroup(pelangganPanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(teksIDPelanggan,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 165,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(teksNama, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(pelangganPanelLayout.createSequentialGroup()
                                                .addGroup(pelangganPanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jComboBox1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(teksTanggalDaftarPelanggan,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 165,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(teksNama2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(pelangganPanelLayout.createSequentialGroup()
                                                .addComponent(buttonHapusPelanggan)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55,
                                                        Short.MAX_VALUE)
                                                .addComponent(buttonUpdatePelanggan)
                                                .addGap(41, 41, 41))))
                        .addGroup(pelangganPanelLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(buttonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(pelangganLabel)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        pelangganPanelLayout.setVerticalGroup(
                pelangganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pelangganPanelLayout.createSequentialGroup()
                                .addGroup(pelangganPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pelangganPanelLayout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(buttonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 23,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(pelangganPanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(pelangganLabel)))
                                .addGap(40, 40, 40)
                                .addGroup(pelangganPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelPilihPelanggan))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pelangganPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelNomorPelanggan)
                                        .addComponent(teksIDPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pelangganPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(teksNama, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelNamaPelanggan1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pelangganPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelTanggalDaftarPelanggan)
                                        .addComponent(teksTanggalDaftarPelanggan,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10,
                                        Short.MAX_VALUE)
                                .addGroup(pelangganPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(teksNama2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelNamaPelanggan2))
                                .addGap(29, 29, 29)
                                .addGroup(pelangganPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(buttonHapusPelanggan)
                                        .addComponent(buttonUpdatePelanggan)
                                        .addComponent(buttonTambahPelanggan))
                                .addGap(50, 50, 50)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pelangganPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pelangganPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void teksNamaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_teksNamaActionPerformed
        // TODO add your handling code here:

    }// GEN-LAST:event_teksNamaActionPerformed

    private void buttonTambahPelangganActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonTambahPelangganActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_buttonTambahPelangganActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox1ActionPerformed
        pelangganValue = (String) jComboBox1.getSelectedItem();
        if (pelangganValue.equals("GUEST")) {
            teksTanggalDaftarPelanggan.setEnabled(false);
            labelTanggalDaftarPelanggan.setEnabled(false);
        }
    }// GEN-LAST:event_jComboBox1ActionPerformed

    private void teksIDPelangganActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_teksIDPelangganActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_teksIDPelangganActionPerformed

    private void buttonBackMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_buttonBackMouseClicked
        Admin a = new Admin();
        a.setVisible(true);
        dispose();
    }// GEN-LAST:event_buttonBackMouseClicked

    private void teksTanggalDaftarPelangganActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_teksTanggalDaftarPelangganActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_teksTanggalDaftarPelangganActionPerformed

    private void teksNama2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_teksNama2ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_teksNama2ActionPerformed

    private void buttonUpdatePelangganActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonUpdatePelangganActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_buttonUpdatePelangganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PelangganAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PelangganAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PelangganAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PelangganAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PelangganAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonHapusPelanggan;
    private javax.swing.JButton buttonTambahPelanggan;
    private javax.swing.JButton buttonUpdatePelanggan;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel labelNamaPelanggan1;
    private javax.swing.JLabel labelNamaPelanggan2;
    private javax.swing.JLabel labelNomorPelanggan;
    private javax.swing.JLabel labelPilihPelanggan;
    private javax.swing.JLabel labelTanggalDaftarPelanggan;
    private javax.swing.JLabel pelangganLabel;
    public static javax.swing.JPanel pelangganPanel;
    private javax.swing.JTextField teksIDPelanggan;
    private javax.swing.JTextField teksNama;
    private javax.swing.JTextField teksNama2;
    private javax.swing.JTextField teksTanggalDaftarPelanggan;
    private String pelangganValue;
    private javax.swing.JLabel tanggalFormat;
    // End of variables declaration//GEN-END:variables

}
