package BackEnd;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class PromosiAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Promosi
     */
    public PromosiAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        promosiPanel = new javax.swing.JPanel();
        promosiLabel = new javax.swing.JLabel();
        buttonBackPromosi = new javax.swing.JButton();
        buttonHapusPromosi = new javax.swing.JButton();
        buttonUpdatePromosi = new javax.swing.JButton();
        labelJenisPromosi = new javax.swing.JLabel();
        labelKodePromo = new javax.swing.JLabel();
        labelTanggalAwal = new javax.swing.JLabel();
        LabelTanggalAkhir = new javax.swing.JLabel();
        labelPersenPotongan = new javax.swing.JLabel();
        labelMaksimumPotongan = new javax.swing.JLabel();
        labelMinimumPotongan = new javax.swing.JLabel();
        buttonTambahPromosi1 = new javax.swing.JButton();
        teksNomorPelanggan = new javax.swing.JTextField();
        teksNomorPelanggan1 = new javax.swing.JTextField();
        teksNomorPelanggan2 = new javax.swing.JTextField();
        teksNomorPelanggan3 = new javax.swing.JTextField();
        teksNomorPelanggan4 = new javax.swing.JTextField();
        teksNomorPelanggan5 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        promosiPanel.setBackground(new java.awt.Color(52, 73, 94));

        promosiLabel.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        promosiLabel.setForeground(new java.awt.Color(255, 255, 255));
        promosiLabel.setText("Promosi");

        buttonBackPromosi.setText("back");
        buttonBackPromosi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackPromosiActionPerformed(evt);
            }
        });

        buttonHapusPromosi.setText("Hapus");

        buttonUpdatePromosi.setText("Update");
        buttonUpdatePromosi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdatePromosiActionPerformed(evt);
            }
        });

        labelJenisPromosi.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        labelJenisPromosi.setForeground(new java.awt.Color(255, 255, 255));
        labelJenisPromosi.setText("Jenis promosi");

        labelKodePromo.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        labelKodePromo.setForeground(new java.awt.Color(255, 255, 255));
        labelKodePromo.setText("Kode promo");

        labelTanggalAwal.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        labelTanggalAwal.setForeground(new java.awt.Color(255, 255, 255));
        labelTanggalAwal.setText("Tanggal awal");

        LabelTanggalAkhir.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        LabelTanggalAkhir.setForeground(new java.awt.Color(255, 255, 255));
        LabelTanggalAkhir.setText("Tanggal akhir");

        labelPersenPotongan.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        labelPersenPotongan.setForeground(new java.awt.Color(255, 255, 255));
        labelPersenPotongan.setText("Persen potongan");

        labelMaksimumPotongan.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        labelMaksimumPotongan.setForeground(new java.awt.Color(255, 255, 255));
        labelMaksimumPotongan.setText("Maksimum potongan");

        labelMinimumPotongan.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        labelMinimumPotongan.setForeground(new java.awt.Color(255, 255, 255));
        labelMinimumPotongan.setText("Minimun potongan");

        buttonTambahPromosi1.setText("Tambah");
        buttonTambahPromosi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahPromosi1ActionPerformed(evt);
            }
        });

        teksNomorPelanggan.setText("nomor pelanggan");
        teksNomorPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teksNomorPelangganActionPerformed(evt);
            }
        });

        teksNomorPelanggan1.setText("nomor pelanggan");
        teksNomorPelanggan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teksNomorPelanggan1ActionPerformed(evt);
            }
        });

        teksNomorPelanggan2.setText("nomor pelanggan");
        teksNomorPelanggan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teksNomorPelanggan2ActionPerformed(evt);
            }
        });

        teksNomorPelanggan3.setText("nomor pelanggan");
        teksNomorPelanggan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teksNomorPelanggan3ActionPerformed(evt);
            }
        });

        teksNomorPelanggan4.setText("nomor pelanggan");
        teksNomorPelanggan4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teksNomorPelanggan4ActionPerformed(evt);
            }
        });

        teksNomorPelanggan5.setText("nomor pelanggan");
        teksNomorPelanggan5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teksNomorPelanggan5ActionPerformed(evt);
            }
        });

        jComboBox1
                .setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DISCOUNT", "CASHBACK", "DELIVERY" }));

        javax.swing.GroupLayout promosiPanelLayout = new javax.swing.GroupLayout(promosiPanel);
        promosiPanel.setLayout(promosiPanelLayout);
        promosiPanelLayout.setHorizontalGroup(
                promosiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(promosiPanelLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(buttonTambahPromosi1)
                                .addGap(52, 52, 52)
                                .addComponent(buttonHapusPromosi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59,
                                        Short.MAX_VALUE)
                                .addComponent(buttonUpdatePromosi)
                                .addGap(35, 35, 35))
                        .addGroup(promosiPanelLayout.createSequentialGroup()
                                .addGroup(promosiPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(promosiPanelLayout.createSequentialGroup()
                                                .addGap(58, 58, 58)
                                                .addGroup(promosiPanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(labelMinimumPotongan)
                                                        .addComponent(LabelTanggalAkhir)
                                                        .addComponent(labelMaksimumPotongan)
                                                        .addComponent(labelPersenPotongan)
                                                        .addComponent(labelTanggalAwal)
                                                        .addComponent(labelKodePromo)
                                                        .addComponent(labelJenisPromosi))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(promosiPanelLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(teksNomorPelanggan5,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 165,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(teksNomorPelanggan4,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 165,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(teksNomorPelanggan3,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 165,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(teksNomorPelanggan2,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 165,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(teksNomorPelanggan1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 165,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(teksNomorPelanggan,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 165,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jComboBox1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(promosiPanelLayout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addComponent(buttonBackPromosi)
                                                .addGap(62, 62, 62)
                                                .addComponent(promosiLabel)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        promosiPanelLayout.setVerticalGroup(
                promosiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(promosiPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(promosiPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(buttonBackPromosi)
                                        .addComponent(promosiLabel))
                                .addGap(5, 5, 5)
                                .addGroup(promosiPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelJenisPromosi)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(promosiPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelKodePromo, javax.swing.GroupLayout.PREFERRED_SIZE, 16,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(teksNomorPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(promosiPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelTanggalAwal)
                                        .addComponent(teksNomorPelanggan1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(promosiPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(LabelTanggalAkhir)
                                        .addComponent(teksNomorPelanggan2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(promosiPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelPersenPotongan)
                                        .addComponent(teksNomorPelanggan3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(promosiPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelMaksimumPotongan)
                                        .addComponent(teksNomorPelanggan4, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(promosiPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelMinimumPotongan)
                                        .addComponent(teksNomorPelanggan5, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(promosiPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(buttonTambahPromosi1)
                                        .addComponent(buttonHapusPromosi)
                                        .addComponent(buttonUpdatePromosi))
                                .addContainerGap(10, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(promosiPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(promosiPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBackPromosiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonBackPromosiActionPerformed
        Admin p = new Admin();
        p.setVisible(true);
        dispose();
    }// GEN-LAST:event_buttonBackPromosiActionPerformed

    private void buttonUpdatePromosiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonUpdatePromosiActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_buttonUpdatePromosiActionPerformed

    private void buttonTambahPromosi1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonTambahPromosi1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_buttonTambahPromosi1ActionPerformed

    private void teksNomorPelangganActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_teksNomorPelangganActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_teksNomorPelangganActionPerformed

    private void teksNomorPelanggan1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_teksNomorPelanggan1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_teksNomorPelanggan1ActionPerformed

    private void teksNomorPelanggan2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_teksNomorPelanggan2ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_teksNomorPelanggan2ActionPerformed

    private void teksNomorPelanggan3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_teksNomorPelanggan3ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_teksNomorPelanggan3ActionPerformed

    private void teksNomorPelanggan4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_teksNomorPelanggan4ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_teksNomorPelanggan4ActionPerformed

    private void teksNomorPelanggan5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_teksNomorPelanggan5ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_teksNomorPelanggan5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PromosiAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PromosiAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PromosiAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PromosiAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PromosiAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelTanggalAkhir;
    private javax.swing.JButton buttonBackPromosi;
    private javax.swing.JButton buttonHapusPromosi;
    private javax.swing.JButton buttonTambahPromosi1;
    private javax.swing.JButton buttonUpdatePromosi;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel labelJenisPromosi;
    private javax.swing.JLabel labelKodePromo;
    private javax.swing.JLabel labelMaksimumPotongan;
    private javax.swing.JLabel labelMinimumPotongan;
    private javax.swing.JLabel labelPersenPotongan;
    private javax.swing.JLabel labelTanggalAwal;
    private javax.swing.JLabel promosiLabel;
    public static javax.swing.JPanel promosiPanel;
    private javax.swing.JTextField teksNomorPelanggan;
    private javax.swing.JTextField teksNomorPelanggan1;
    private javax.swing.JTextField teksNomorPelanggan2;
    private javax.swing.JTextField teksNomorPelanggan3;
    private javax.swing.JTextField teksNomorPelanggan4;
    private javax.swing.JTextField teksNomorPelanggan5;
    // End of variables declaration//GEN-END:variables
}
